---
# Welcome to CustomCraft by refaltor
# You can use items with a meta, example: `1:5`
# Infinite Configuration
# a problem ? discord.gg/goldrush


crafts:
  grass:
    shape:
      - [["3"], ["3"], ["3"]]
      - [["3"], ["325:8"], ["3"]]
      - [["3"], ["3"], ["3"]]
    result: ["2:0", 1, "name custom"] # custom name is not required, to disable the custom name, remove the string
...